export const AUTH_ATTEMPTING = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAILED ='AUTH_FAILED';
export const USER_LOGGED_OUT ='USER_LOGGED_OUT';
export const PROFILE_FETCH ='PROFILE_FETCH';
export const BRAND_SAVED = 'BRAND_SAVED';
export const BRAND_UPDATED = 'BRAND_UPDATED';
export const AMBASSADOR_SAVED = 'AMBASSADOR_SAVED';
export const AMBASSADOR_UPDATED = 'AMBASSADOR_UPDATED';
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS  ='CLEAR_ERRORS';

export const FETCHING_BRAND = 'FETCHING_BRAND';
export const FETCHING_AMBASSADOR = 'FETCHING_AMBASSADOR';
export const FETCHED_SUCCESS = 'FETCHED_SUCCESS';
export const FETCHED_FAILED  ='FETCHED_FAILED';

export const UPLOAD_FILE  ='UPLOAD_FILE';